# Generated by Django 4.1.6 on 2023-02-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
